# Local Docker Compose Simulation
#
# Simulates a local development deployment with reservoir mode.
#
# Total: 200 connections across 4 services
# Expected convergence: ~2 seconds

seed: 42
endpoint: cluster.dsql.eu-west-1.on.aws

duration: 20m
sampleEvery: 1s

limiterPerSec: 100

assertMaxConnectsPerSec: 100
assertConvergeWithin: 60s
assertStableFor: 5s
assertZeroEmptyEvents: true

scenario:
  kind: cold_start

services:
  - name: history
    targetReady: 50
    guardWindow: 45s
    baseLifetime: 11m
    jitter: 2m
    startDelay: 0s

  - name: matching
    targetReady: 50
    guardWindow: 45s
    baseLifetime: 11m
    jitter: 2m
    startDelay: 100ms

  - name: frontend
    targetReady: 50
    guardWindow: 45s
    baseLifetime: 11m
    jitter: 2m
    startDelay: 200ms

  - name: worker
    targetReady: 50
    guardWindow: 45s
    baseLifetime: 11m
    jitter: 2m
    startDelay: 300ms
